// products.js
const products = [
    {
      id: 1,
      name: "Stylish Sofa Set",
      price: 15000,
      description: "A stylish and comfortable sofa.",
      image: "product1.jpg",
      category: "furniture",
    },
    {
      id: 2,
      name: "Modern Floor Lamp",
      price: 3500,
      description: "A sleek and modern floor lamp.",
      image: "product2.jpg",
      category: "lighting",
    },
    {
        id: 3,
        name: "Stylish Set",
        price: 1500,
        description: "A stylish and comfortable sofa.",
        image: "product3.jpg",
        category: "furniture",
      },
      {
        id: 4,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },
      {
        id: 5,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },
      {
        id: 6,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },
      {
        id: 7,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },
      {
        id: 8,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },
      {
        id: 3,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },{
        id: 3,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },{
        id: 3,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },{
        id: 3,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },{
        id: 3,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },{
        id: 3,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },{
        id: 3,
        name: "Stylish Sofa Set",
        price: 15000,
        description: "A stylish and comfortable sofa.",
        image: "product1.jpg",
        category: "furniture",
      },
    // Add other products...
  ];